//! Emit LLVM IR text from Kroa IR.

use crate::diagnostics::Diagnostics;
use crate::ir::*;
use crate::typecheck::Type;
use std::collections::HashMap;
use std::fmt::Write as _;

pub fn emit_llvm(module: &Module, diagnostics: &mut Diagnostics) -> Option<String> {
    let mut emitter = Emitter {
        diagnostics,
        out: String::new(),
        struct_types: HashMap::new(),
        enum_types: HashMap::new(),
        enum_infos: HashMap::new(),
        value_names: HashMap::new(),
        value_types: HashMap::new(),
        ptr_elem: HashMap::new(),
        next_temp: 0,
        string_globals: Vec::new(),
    };
    emitter.emit_module(module);
    if emitter.diagnostics.has_errors() {
        None
    } else {
        Some(emitter.finish())
    }
}

struct Emitter<'a> {
    diagnostics: &'a mut Diagnostics,
    out: String,
    struct_types: HashMap<String, String>,
    enum_types: HashMap<String, String>,
    enum_infos: HashMap<String, crate::typecheck::EnumInfo>,
    value_names: HashMap<ValueId, String>,
    value_types: HashMap<ValueId, Type>,
    ptr_elem: HashMap<ValueId, Type>,
    next_temp: u32,
    string_globals: Vec<(String, String)>,
}

impl<'a> Emitter<'a> {
    fn emit_module(&mut self, module: &Module) {
        let _ = writeln!(self.out, "; Generated by the Kroa compiler");
        let _ = writeln!(
            self.out,
            "target datalayout = \"e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128\""
        );
        let _ = writeln!(self.out, "target triple = \"x86_64-pc-windows-msvc\"");
        let _ = writeln!(self.out);

        let _ = writeln!(self.out, "declare void @kroa_print_i64(i64)");
        let _ = writeln!(self.out, "declare void @kroa_print_f64(double)");
        let _ = writeln!(self.out, "declare void @kroa_print_bool(i1)");
        let _ = writeln!(self.out, "declare void @kroa_print_str(ptr, i64)");
        let _ = writeln!(self.out, "declare void @kroa_arena_enter()");
        let _ = writeln!(self.out, "declare void @kroa_arena_exit()");
        let _ = writeln!(self.out, "declare ptr @kroa_arena_alloc(i64)");
        let _ = writeln!(self.out, "declare ptr @kroa_str_to_cstr(ptr, i64)");
        let _ = writeln!(self.out, "declare void @kroa_bounds_panic(i64, i64)");
        let _ = writeln!(
            self.out,
            "declare void @kroa_slice_bounds_panic(i64, i64, i64)"
        );
        let _ = writeln!(self.out);

        for (name, info) in &module.structs {
            let fields: Vec<String> = info.fields.iter().map(|(_, t)| self.ty(t)).collect();
            let lty = format!("%struct.{name}");
            let _ = writeln!(self.out, "{lty} = type {{ {} }}", fields.join(", "));
            self.struct_types.insert(name.clone(), lty);
        }
        if !module.structs.is_empty() {
            let _ = writeln!(self.out);
        }

        // Snapshot enum infos and reserve type names before emitting bodies
        // so mutually-referencing enums resolve.
        let mut enum_names: Vec<_> = module.enums.keys().cloned().collect();
        enum_names.sort();
        for name in &enum_names {
            let info = module.enums.get(name).unwrap().clone();
            self.enum_infos.insert(name.clone(), info);
            self.enum_types
                .insert(name.clone(), format!("%enum.{name}"));
        }
        for name in &enum_names {
            let info = self.enum_infos.get(name).unwrap().clone();
            let mut parts = vec!["i32".to_string()];
            for v in &info.variants {
                for (_, t) in &v.fields {
                    parts.push(self.ty(t));
                }
            }
            let lty = self.enum_types.get(name).unwrap().clone();
            let _ = writeln!(self.out, "{lty} = type {{ {} }}", parts.join(", "));
        }
        if !module.enums.is_empty() {
            let _ = writeln!(self.out);
        }

        for ext in &module.externs {
            let params: Vec<String> = ext
                .params
                .iter()
                .map(|t| match t {
                    Type::Struct(name) => {
                        let sty = self
                            .struct_types
                            .get(name)
                            .cloned()
                            .unwrap_or_else(|| format!("%struct.{name}"));
                        // Windows x64 ABI: aggregates > 8 bytes are passed by pointer/byval.
                        format!("ptr byval({sty}) align 8")
                    }
                    _ => self.ty(t),
                })
                .collect();
            let ret = self.ret_ty(&ext.return_type);
            let _ = writeln!(
                self.out,
                "declare {ret} @{}({})",
                mangle(&ext.name),
                params.join(", ")
            );
        }

        // Builtin aliases used from Kroa source names.
        // print_* map to runtime symbols below at call sites.

        for func in &module.functions {
            self.emit_function(func, module);
            let _ = writeln!(self.out);
        }
    }

    fn finish(self) -> String {
        // Keep target triple at the top. Insert string globals after the header
        // comment / datalayout / triple / blank line.
        if self.string_globals.is_empty() {
            return self.out;
        }
        let mut globals = String::new();
        for (name, content) in &self.string_globals {
            let escaped = llvm_escape(content);
            let len = content.len() + 1;
            let _ = writeln!(
                globals,
                "@{name} = private unnamed_addr constant [{len} x i8] c\"{escaped}\\00\""
            );
        }
        globals.push('\n');

        // Insert after the first blank line following target triple.
        if let Some(idx) = self.out.find("\n\n") {
            let (head, tail) = self.out.split_at(idx + 2);
            format!("{head}{globals}{tail}")
        } else {
            globals + &self.out
        }
    }

    fn emit_function(&mut self, func: &Function, module: &Module) {
        self.value_names.clear();
        self.value_types.clear();
        self.ptr_elem.clear();
        self.next_temp = 0;

        let params: Vec<String> = func
            .params
            .iter()
            .map(|(name, ty, vid)| {
                let llvm_name = format!("%arg_{name}");
                self.value_names.insert(*vid, llvm_name.clone());
                self.value_types.insert(*vid, ty.clone());
                format!("{} {llvm_name}", self.ty(ty))
            })
            .collect();
        let ret = self.ret_ty(&func.return_type);
        let _ = writeln!(
            self.out,
            "define {ret} @{}({}) {{",
            mangle(&func.name),
            params.join(", ")
        );

        for block in &func.blocks {
            let _ = writeln!(self.out, "{}:", block_label(block));
            for inst in &block.insts {
                self.emit_inst(inst, module);
            }
            self.emit_term(&block.terminator, &func.return_type);
        }
        let _ = writeln!(self.out, "}}");
    }

    fn emit_inst(&mut self, inst: &Inst, module: &Module) {
        match &inst.kind {
            InstKind::Nop => {
                if let Some(id) = inst.id {
                    // Unit value placeholder
                    let name = self.name_of(id);
                    let _ = writeln!(self.out, "  {name} = add i64 0, 0");
                    self.value_types.insert(id, Type::Unit);
                }
            }
            InstKind::ConstI64(v) => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let _ = writeln!(self.out, "  {name} = add i64 0, {v}");
                self.value_types.insert(id, Type::I64);
            }
            InstKind::ConstF64(v) => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let _ = writeln!(self.out, "  {name} = fadd double 0.0, {v}");
                self.value_types.insert(id, Type::F64);
            }
            InstKind::ConstBool(v) => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let bit = if *v { 1 } else { 0 };
                let _ = writeln!(self.out, "  {name} = add i1 0, {bit}");
                self.value_types.insert(id, Type::Bool);
            }
            InstKind::ConstStr(s) => {
                let id = inst.id.unwrap();
                let gname = format!(".str.{}", self.string_globals.len());
                self.string_globals.push((gname.clone(), s.clone()));
                let ptr_name = self.temp();
                let len = s.len();
                let _ = writeln!(
                    self.out,
                    "  {ptr_name} = getelementptr inbounds [{} x i8], ptr @{gname}, i64 0, i64 0",
                    len + 1
                );
                // Represent str as {ptr, len} stored in two SSA values packed via insertvalue.
                let name = self.name_of(id);
                let _ = writeln!(
                    self.out,
                    "  {name} = insertvalue {{ ptr, i64 }} {{ ptr poison, i64 {len} }}, ptr {ptr_name}, 0"
                );
                self.value_types.insert(id, Type::Str);
            }
            InstKind::Alloca => {
                let id = inst.id.unwrap();
                let elem = &inst.ty;
                let name = self.name_of(id);
                let _ = writeln!(self.out, "  {name} = alloca {}", self.ty(elem));
                self.ptr_elem.insert(id, elem.clone());
                self.value_types.insert(
                    id,
                    Type::Ref {
                        mutable: true,
                        inner: Box::new(elem.clone()),
                    },
                );
            }
            InstKind::Load { ptr } => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let elem = self
                    .ptr_elem
                    .get(ptr)
                    .cloned()
                    .unwrap_or_else(|| inst.ty.clone());
                let pname = self.lookup(*ptr);
                let _ = writeln!(self.out, "  {name} = load {}, ptr {pname}", self.ty(&elem));
                self.value_types.insert(id, elem);
            }
            InstKind::Store { ptr, value } => {
                let pname = self.lookup(*ptr);
                let vname = self.lookup(*value);
                let elem = self
                    .ptr_elem
                    .get(ptr)
                    .cloned()
                    .or_else(|| self.value_types.get(value).cloned())
                    .unwrap_or(Type::I64);
                let _ = writeln!(self.out, "  store {} {vname}, ptr {pname}", self.ty(&elem));
            }
            InstKind::Binary { op, left, right } => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let lt = self.value_types.get(left).cloned().unwrap_or(Type::I64);
                let l = self.lookup(*left);
                let r = self.lookup(*right);
                let (instr, out_ty) = match (op, &lt) {
                    (BinOp::Add, Type::F64) => ("fadd", Type::F64),
                    (BinOp::Sub, Type::F64) => ("fsub", Type::F64),
                    (BinOp::Mul, Type::F64) => ("fmul", Type::F64),
                    (BinOp::Div, Type::F64) => ("fdiv", Type::F64),
                    (BinOp::Rem, Type::F64) => ("frem", Type::F64),
                    (BinOp::Add, _) => ("add", Type::I64),
                    (BinOp::Sub, _) => ("sub", Type::I64),
                    (BinOp::Mul, _) => ("mul", Type::I64),
                    (BinOp::Div, _) => ("sdiv", Type::I64),
                    (BinOp::Rem, _) => ("srem", Type::I64),
                    (BinOp::Eq, Type::F64) => ("fcmp oeq", Type::Bool),
                    (BinOp::NotEq, Type::F64) => ("fcmp one", Type::Bool),
                    (BinOp::Lt, Type::F64) => ("fcmp olt", Type::Bool),
                    (BinOp::LtEq, Type::F64) => ("fcmp ole", Type::Bool),
                    (BinOp::Gt, Type::F64) => ("fcmp ogt", Type::Bool),
                    (BinOp::GtEq, Type::F64) => ("fcmp oge", Type::Bool),
                    (BinOp::Eq, Type::Bool) => ("icmp eq", Type::Bool),
                    (BinOp::NotEq, Type::Bool) => ("icmp ne", Type::Bool),
                    (BinOp::Eq, _) => ("icmp eq", Type::Bool),
                    (BinOp::NotEq, _) => ("icmp ne", Type::Bool),
                    (BinOp::Lt, _) => ("icmp slt", Type::Bool),
                    (BinOp::LtEq, _) => ("icmp sle", Type::Bool),
                    (BinOp::Gt, _) => ("icmp sgt", Type::Bool),
                    (BinOp::GtEq, _) => ("icmp sge", Type::Bool),
                    (BinOp::And, _) => ("and", Type::Bool),
                    (BinOp::Or, _) => ("or", Type::Bool),
                };
                let lty = self.ty(&lt);
                let _ = writeln!(self.out, "  {name} = {instr} {lty} {l}, {r}");
                self.value_types.insert(id, out_ty);
            }
            InstKind::Unary { op, value } => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let vt = self.value_types.get(value).cloned().unwrap_or(Type::I64);
                let v = self.lookup(*value);
                match op {
                    UnOp::Neg => {
                        if vt == Type::F64 {
                            let _ = writeln!(self.out, "  {name} = fneg double {v}");
                            self.value_types.insert(id, Type::F64);
                        } else {
                            let _ = writeln!(self.out, "  {name} = sub i64 0, {v}");
                            self.value_types.insert(id, Type::I64);
                        }
                    }
                    UnOp::Not => {
                        let _ = writeln!(self.out, "  {name} = xor i1 {v}, true");
                        self.value_types.insert(id, Type::Bool);
                    }
                }
            }
            InstKind::Call {
                name: fname,
                args,
                is_extern,
            } => {
                let arg_tys: Vec<Type> = args
                    .iter()
                    .map(|a| self.value_types.get(a).cloned().unwrap_or(Type::I64))
                    .collect();
                let is_c_extern = *is_extern || module.externs.iter().any(|e| e.name == *fname);
                let arg_list: Vec<String> = args
                    .iter()
                    .zip(arg_tys.iter())
                    .map(|(a, t)| match t {
                        Type::Struct(name) if is_c_extern => {
                            let sty = self
                                .struct_types
                                .get(name)
                                .cloned()
                                .unwrap_or_else(|| format!("%struct.{name}"));
                            let tmp = self.temp();
                            let _ = writeln!(self.out, "  {tmp} = alloca {sty}");
                            let _ =
                                writeln!(self.out, "  store {sty} {}, ptr {tmp}", self.lookup(*a));
                            format!("ptr byval({sty}) align 8 {tmp}")
                        }
                        _ => format!("{} {}", self.ty(t), self.lookup(*a)),
                    })
                    .collect();

                let (llvm_name, ret_ty) = match fname.as_str() {
                    "print_i64" => ("kroa_print_i64", Type::Unit),
                    "print_f64" => ("kroa_print_f64", Type::Unit),
                    "print_bool" => ("kroa_print_bool", Type::Unit),
                    "print_str" => {
                        // Expand {ptr,i64} str into two args.
                        let s = self.lookup(args[0]);
                        let p = self.temp();
                        let l = self.temp();
                        let _ = writeln!(self.out, "  {p} = extractvalue {{ ptr, i64 }} {s}, 0");
                        let _ = writeln!(self.out, "  {l} = extractvalue {{ ptr, i64 }} {s}, 1");
                        if let Some(id) = inst.id {
                            let name = self.name_of(id);
                            let _ =
                                writeln!(self.out, "  call void @kroa_print_str(ptr {p}, i64 {l})");
                            let _ = writeln!(self.out, "  {name} = add i64 0, 0");
                            self.value_types.insert(id, Type::Unit);
                        } else {
                            let _ =
                                writeln!(self.out, "  call void @kroa_print_str(ptr {p}, i64 {l})");
                        }
                        return;
                    }
                    other => {
                        let ret = module
                            .functions
                            .iter()
                            .find(|f| f.name == other)
                            .map(|f| f.return_type.clone())
                            .or_else(|| {
                                module
                                    .externs
                                    .iter()
                                    .find(|f| f.name == other)
                                    .map(|f| f.return_type.clone())
                            })
                            .unwrap_or(inst.ty.clone());
                        (other, ret)
                    }
                };

                if ret_ty == Type::Unit {
                    let _ = writeln!(
                        self.out,
                        "  call void @{}({})",
                        mangle(llvm_name),
                        arg_list.join(", ")
                    );
                    if let Some(id) = inst.id {
                        let name = self.name_of(id);
                        let _ = writeln!(self.out, "  {name} = add i64 0, 0");
                        self.value_types.insert(id, Type::Unit);
                    }
                } else {
                    let id = inst.id.unwrap();
                    let name = self.name_of(id);
                    let _ = writeln!(
                        self.out,
                        "  {name} = call {} @{}({})",
                        self.ty(&ret_ty),
                        mangle(llvm_name),
                        arg_list.join(", ")
                    );
                    self.value_types.insert(id, ret_ty);
                }
            }
            InstKind::StructAgg { name, fields } => {
                let id = inst.id.unwrap();
                let sty = self
                    .struct_types
                    .get(name)
                    .cloned()
                    .unwrap_or_else(|| format!("%struct.{name}"));
                let mut cur = "poison".to_string();
                for (i, f) in fields.iter().enumerate() {
                    let next = if i + 1 == fields.len() {
                        self.name_of(id)
                    } else {
                        self.temp()
                    };
                    let fv = self.lookup(*f);
                    let _ = writeln!(
                        self.out,
                        "  {next} = insertvalue {sty} {cur}, {} {fv}, {i}",
                        self.ty(self.value_types.get(f).unwrap_or(&Type::I64))
                    );
                    cur = next;
                }
                if fields.is_empty() {
                    let namev = self.name_of(id);
                    let _ = writeln!(self.out, "  {namev} = insertvalue {sty} poison, i64 0, 0");
                }
                self.value_types.insert(id, Type::Struct(name.clone()));
            }
            InstKind::ExtractField { agg, index } => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let at = self.value_types.get(agg).cloned().unwrap_or(Type::I64);
                let an = self.lookup(*agg);
                let _ = writeln!(
                    self.out,
                    "  {name} = extractvalue {} {an}, {index}",
                    self.ty(&at)
                );
                self.value_types.insert(id, inst.ty.clone());
            }
            InstKind::InsertField { agg, index, value } => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let at = self.value_types.get(agg).cloned().unwrap_or(Type::I64);
                let an = self.lookup(*agg);
                let vn = self.lookup(*value);
                let vt = self.value_types.get(value).cloned().unwrap_or(Type::I64);
                let _ = writeln!(
                    self.out,
                    "  {name} = insertvalue {} {an}, {} {vn}, {index}",
                    self.ty(&at),
                    self.ty(&vt)
                );
                self.value_types.insert(id, at);
            }
            InstKind::Cast { value, to } => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let from = self.value_types.get(value).cloned().unwrap_or(Type::I64);
                let v = self.lookup(*value);
                match (&from, to) {
                    (Type::I64, Type::F64) => {
                        let _ = writeln!(self.out, "  {name} = sitofp i64 {v} to double");
                    }
                    (Type::F64, Type::I64) => {
                        let _ = writeln!(self.out, "  {name} = fptosi double {v} to i64");
                    }
                    (Type::Bool, Type::I64) => {
                        let _ = writeln!(self.out, "  {name} = zext i1 {v} to i64");
                    }
                    _ => {
                        let _ = writeln!(
                            self.out,
                            "  {name} = bitcast {} {v} to {}",
                            self.ty(&from),
                            self.ty(to)
                        );
                    }
                }
                self.value_types.insert(id, to.clone());
            }
            InstKind::Move { value } => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let vt = self
                    .value_types
                    .get(value)
                    .cloned()
                    .unwrap_or(inst.ty.clone());
                let v = self.lookup(*value);
                match &vt {
                    Type::F64 => {
                        let _ = writeln!(self.out, "  {name} = fadd double {v}, 0.0");
                    }
                    Type::Bool => {
                        let _ = writeln!(self.out, "  {name} = or i1 {v}, false");
                    }
                    Type::I64 | Type::Unit | Type::CChar => {
                        let _ = writeln!(self.out, "  {name} = add i64 {v}, 0");
                    }
                    Type::CString => {
                        let _ = writeln!(self.out, "  {name} = getelementptr i8, ptr {v}, i64 0");
                    }
                    Type::Ref { inner, .. } => {
                        if matches!(inner.as_ref(), Type::Slice(_)) {
                            let p = self.temp();
                            let _ =
                                writeln!(self.out, "  {p} = extractvalue {{ ptr, i64 }} {v}, 0");
                            let _ = writeln!(
                                self.out,
                                "  {name} = insertvalue {{ ptr, i64 }} {v}, ptr {p}, 0"
                            );
                        } else {
                            let _ =
                                writeln!(self.out, "  {name} = getelementptr i8, ptr {v}, i64 0");
                        }
                    }
                    Type::Str | Type::Slice(_) => {
                        let p = self.temp();
                        let _ = writeln!(self.out, "  {p} = extractvalue {{ ptr, i64 }} {v}, 0");
                        let _ = writeln!(
                            self.out,
                            "  {name} = insertvalue {{ ptr, i64 }} {v}, ptr {p}, 0"
                        );
                    }
                    Type::Array { .. } => {
                        let aty = self.ty(&vt);
                        let _ = writeln!(
                            self.out,
                            "  {name} = select i1 true, {aty} {v}, {aty} poison"
                        );
                    }
                    Type::Enum(ename) | Type::Struct(ename) | Type::Named(ename) => {
                        let sty = if matches!(vt, Type::Enum(_)) {
                            self.enum_types
                                .get(ename)
                                .cloned()
                                .unwrap_or_else(|| format!("%enum.{ename}"))
                        } else {
                            self.struct_types
                                .get(ename)
                                .cloned()
                                .unwrap_or_else(|| format!("%struct.{ename}"))
                        };
                        let p = self.temp();
                        let _ = writeln!(self.out, "  {p} = extractvalue {sty} {v}, 0");
                        let _ = writeln!(
                            self.out,
                            "  {name} = select i1 true, {sty} {v}, {sty} poison"
                        );
                        let _ = p;
                    }
                }
                self.value_types.insert(id, vt);
            }
            InstKind::Ref { place, .. } => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let p = self.lookup(*place);
                // Fat-pointer refs (`&[T]`) copy the slice value from the place.
                if let Type::Ref { inner, .. } = &inst.ty {
                    if matches!(inner.as_ref(), Type::Slice(_)) {
                        let _ = writeln!(self.out, "  {name} = load {{ ptr, i64 }}, ptr {p}");
                        self.value_types.insert(id, inst.ty.clone());
                        self.ptr_elem.insert(id, *inner.clone());
                        return;
                    }
                }
                let _ = writeln!(self.out, "  {name} = getelementptr i8, ptr {p}, i64 0");
                if let Some(elem) = self.ptr_elem.get(place).cloned() {
                    self.ptr_elem.insert(id, elem.clone());
                    self.value_types.insert(
                        id,
                        Type::Ref {
                            mutable: true,
                            inner: Box::new(elem),
                        },
                    );
                } else {
                    self.value_types.insert(id, inst.ty.clone());
                    if let Type::Ref { inner, .. } = &inst.ty {
                        self.ptr_elem.insert(id, *inner.clone());
                    }
                }
            }
            InstKind::Deref { ptr } => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let elem = self
                    .ptr_elem
                    .get(ptr)
                    .cloned()
                    .unwrap_or_else(|| inst.ty.clone());
                let p = self.lookup(*ptr);
                let _ = writeln!(self.out, "  {name} = load {}, ptr {p}", self.ty(&elem));
                self.value_types.insert(id, elem);
            }
            InstKind::ArenaEnter => {
                let _ = writeln!(self.out, "  call void @kroa_arena_enter()");
            }
            InstKind::ArenaExit => {
                let _ = writeln!(self.out, "  call void @kroa_arena_exit()");
            }
            InstKind::ArenaAlloc { nbytes } => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let n = self.lookup(*nbytes);
                let _ = writeln!(self.out, "  {name} = call ptr @kroa_arena_alloc(i64 {n})");
                self.value_types.insert(
                    id,
                    Type::Ref {
                        mutable: true,
                        inner: Box::new(Type::I64),
                    },
                );
            }
            InstKind::ToCString { value } => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let s = self.lookup(*value);
                let p = self.temp();
                let l = self.temp();
                let _ = writeln!(self.out, "  {p} = extractvalue {{ ptr, i64 }} {s}, 0");
                let _ = writeln!(self.out, "  {l} = extractvalue {{ ptr, i64 }} {s}, 1");
                let _ = writeln!(
                    self.out,
                    "  {name} = call ptr @kroa_str_to_cstr(ptr {p}, i64 {l})"
                );
                self.value_types.insert(id, Type::CString);
            }
            InstKind::ArrayAgg { elems } => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let arr_ty = self.ty(&inst.ty);
                let elem_ty = match &inst.ty {
                    Type::Array { element, .. } => self.ty(element),
                    _ => "i64".into(),
                };
                let mut cur = String::from("poison");
                for (i, e) in elems.iter().enumerate() {
                    let en = self.lookup(*e);
                    let tmp = if i + 1 == elems.len() {
                        name.clone()
                    } else {
                        self.temp()
                    };
                    let _ = writeln!(
                        self.out,
                        "  {tmp} = insertvalue {arr_ty} {cur}, {elem_ty} {en}, {i}"
                    );
                    cur = tmp;
                }
                if elems.is_empty() {
                    let _ = writeln!(
                        self.out,
                        "  {name} = select i1 true, {arr_ty} poison, {arr_ty} poison"
                    );
                }
                self.value_types.insert(id, inst.ty.clone());
            }
            InstKind::Len { value } => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let vt = self.value_types.get(value).cloned().unwrap_or(Type::I64);
                let v = self.lookup(*value);
                match &vt {
                    Type::Array { len, .. } => {
                        let _ = writeln!(self.out, "  {name} = add i64 0, {len}");
                    }
                    Type::Slice(_) | Type::Str => {
                        let _ = writeln!(self.out, "  {name} = extractvalue {{ ptr, i64 }} {v}, 1");
                    }
                    Type::Ref { inner, .. } if matches!(inner.as_ref(), Type::Slice(_)) => {
                        let _ = writeln!(self.out, "  {name} = extractvalue {{ ptr, i64 }} {v}, 1");
                    }
                    Type::Ref { inner, .. } => match inner.as_ref() {
                        Type::Array { len, .. } => {
                            let _ = writeln!(self.out, "  {name} = add i64 0, {len}");
                        }
                        _ => {
                            let loaded = self.temp();
                            let _ = writeln!(self.out, "  {loaded} = load {{ ptr, i64 }}, ptr {v}");
                            let _ = writeln!(
                                self.out,
                                "  {name} = extractvalue {{ ptr, i64 }} {loaded}, 1"
                            );
                        }
                    },
                    _ => {
                        // Pointer to a slice value (alloca of {ptr,i64}).
                        let loaded = self.temp();
                        let _ = writeln!(self.out, "  {loaded} = load {{ ptr, i64 }}, ptr {v}");
                        let _ = writeln!(
                            self.out,
                            "  {name} = extractvalue {{ ptr, i64 }} {loaded}, 1"
                        );
                    }
                }
                self.value_types.insert(id, Type::I64);
            }
            InstKind::BoundsCheck { index, len } => {
                let idx = self.lookup(*index);
                let ln = self.lookup(*len);
                let neg = self.temp();
                let oob = self.temp();
                let bad = self.temp();
                let ok_lbl = format!("bounds.ok.{}", self.next_temp);
                let bad_lbl = format!("bounds.bad.{}", self.next_temp);
                self.next_temp += 1;
                let _ = writeln!(self.out, "  {neg} = icmp slt i64 {idx}, 0");
                let _ = writeln!(self.out, "  {oob} = icmp sge i64 {idx}, {ln}");
                let _ = writeln!(self.out, "  {bad} = or i1 {neg}, {oob}");
                let _ = writeln!(self.out, "  br i1 {bad}, label %{bad_lbl}, label %{ok_lbl}");
                let _ = writeln!(self.out, "{bad_lbl}:");
                let _ = writeln!(
                    self.out,
                    "  call void @kroa_bounds_panic(i64 {idx}, i64 {ln})"
                );
                let _ = writeln!(self.out, "  unreachable");
                let _ = writeln!(self.out, "{ok_lbl}:");
            }
            InstKind::SliceBoundsCheck { start, end, len } => {
                let s = self.lookup(*start);
                let e = self.lookup(*end);
                let ln = self.lookup(*len);
                let s_neg = self.temp();
                let e_neg = self.temp();
                let s_gt_e = self.temp();
                let e_gt_l = self.temp();
                let t1 = self.temp();
                let t2 = self.temp();
                let bad = self.temp();
                let ok_lbl = format!("slice.ok.{}", self.next_temp);
                let bad_lbl = format!("slice.bad.{}", self.next_temp);
                self.next_temp += 1;
                let _ = writeln!(self.out, "  {s_neg} = icmp slt i64 {s}, 0");
                let _ = writeln!(self.out, "  {e_neg} = icmp slt i64 {e}, 0");
                let _ = writeln!(self.out, "  {s_gt_e} = icmp sgt i64 {s}, {e}");
                let _ = writeln!(self.out, "  {e_gt_l} = icmp sgt i64 {e}, {ln}");
                let _ = writeln!(self.out, "  {t1} = or i1 {s_neg}, {e_neg}");
                let _ = writeln!(self.out, "  {t2} = or i1 {s_gt_e}, {e_gt_l}");
                let _ = writeln!(self.out, "  {bad} = or i1 {t1}, {t2}");
                let _ = writeln!(self.out, "  br i1 {bad}, label %{bad_lbl}, label %{ok_lbl}");
                let _ = writeln!(self.out, "{bad_lbl}:");
                let _ = writeln!(
                    self.out,
                    "  call void @kroa_slice_bounds_panic(i64 {s}, i64 {e}, i64 {ln})"
                );
                let _ = writeln!(self.out, "  unreachable");
                let _ = writeln!(self.out, "{ok_lbl}:");
            }
            InstKind::ElemPtr { base, index } => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let idx = self.lookup(*index);
                let base_n = self.lookup(*base);
                let base_ty = self
                    .ptr_elem
                    .get(base)
                    .cloned()
                    .or_else(|| self.value_types.get(base).cloned())
                    .unwrap_or(Type::I64);
                let (elem_ty, ptr) = match &base_ty {
                    Type::Array { element, len } => {
                        let aty = format!("[{len} x {}]", self.ty(element));
                        let p = self.temp();
                        let _ = writeln!(
                            self.out,
                            "  {p} = getelementptr inbounds {aty}, ptr {base_n}, i64 0, i64 {idx}"
                        );
                        (*element.clone(), p)
                    }
                    Type::Ref { inner, .. } => match inner.as_ref() {
                        Type::Array { element, len } => {
                            let aty = format!("[{len} x {}]", self.ty(element));
                            let p = self.temp();
                            let _ = writeln!(
                                self.out,
                                "  {p} = getelementptr inbounds {aty}, ptr {base_n}, i64 0, i64 {idx}"
                            );
                            (element.as_ref().clone(), p)
                        }
                        Type::Slice(element) => {
                            // Fat-pointer ref value in SSA.
                            let data = self.temp();
                            let p = self.temp();
                            let et = self.ty(element);
                            let _ = writeln!(
                                self.out,
                                "  {data} = extractvalue {{ ptr, i64 }} {base_n}, 0"
                            );
                            let _ = writeln!(
                                self.out,
                                "  {p} = getelementptr inbounds {et}, ptr {data}, i64 {idx}"
                            );
                            (element.as_ref().clone(), p)
                        }
                        other => (other.clone(), base_n),
                    },
                    Type::Slice(element) => {
                        // base is a slice value in SSA.
                        let data = self.temp();
                        let p = self.temp();
                        let et = self.ty(element);
                        let _ = writeln!(
                            self.out,
                            "  {data} = extractvalue {{ ptr, i64 }} {base_n}, 0"
                        );
                        let _ = writeln!(
                            self.out,
                            "  {p} = getelementptr inbounds {et}, ptr {data}, i64 {idx}"
                        );
                        (*element.clone(), p)
                    }
                    _ => {
                        // Assume pointer to slice aggregate.
                        let loaded = self.temp();
                        let data = self.temp();
                        let p = self.temp();
                        let et = match &inst.ty {
                            Type::Ref { inner, .. } => self.ty(inner),
                            _ => "i64".into(),
                        };
                        let _ =
                            writeln!(self.out, "  {loaded} = load {{ ptr, i64 }}, ptr {base_n}");
                        let _ = writeln!(
                            self.out,
                            "  {data} = extractvalue {{ ptr, i64 }} {loaded}, 0"
                        );
                        let _ = writeln!(
                            self.out,
                            "  {p} = getelementptr inbounds {et}, ptr {data}, i64 {idx}"
                        );
                        (Type::I64, p)
                    }
                };
                let _ = writeln!(self.out, "  {name} = getelementptr i8, ptr {ptr}, i64 0");
                self.ptr_elem.insert(id, elem_ty.clone());
                self.value_types.insert(
                    id,
                    Type::Ref {
                        mutable: true,
                        inner: Box::new(elem_ty),
                    },
                );
            }
            InstKind::SliceFrom { base, start, end } => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let s = self.lookup(*start);
                let e = self.lookup(*end);
                let base_n = self.lookup(*base);
                let base_ty = self
                    .ptr_elem
                    .get(base)
                    .cloned()
                    .or_else(|| self.value_types.get(base).cloned())
                    .unwrap_or(Type::I64);
                let len_tmp = self.temp();
                let _ = writeln!(self.out, "  {len_tmp} = sub i64 {e}, {s}");
                let data_ptr = match &base_ty {
                    Type::Array { element, len } => {
                        let aty = format!("[{len} x {}]", self.ty(element));
                        let p = self.temp();
                        let _ = writeln!(
                            self.out,
                            "  {p} = getelementptr inbounds {aty}, ptr {base_n}, i64 0, i64 {s}"
                        );
                        p
                    }
                    Type::Ref { inner, .. } => match inner.as_ref() {
                        Type::Array { element, len } => {
                            let aty = format!("[{len} x {}]", self.ty(element));
                            let p = self.temp();
                            let _ = writeln!(
                                self.out,
                                "  {p} = getelementptr inbounds {aty}, ptr {base_n}, i64 0, i64 {s}"
                            );
                            p
                        }
                        Type::Slice(element) => {
                            let data = self.temp();
                            let p = self.temp();
                            let et = self.ty(element);
                            let _ = writeln!(
                                self.out,
                                "  {data} = extractvalue {{ ptr, i64 }} {base_n}, 0"
                            );
                            let _ = writeln!(
                                self.out,
                                "  {p} = getelementptr inbounds {et}, ptr {data}, i64 {s}"
                            );
                            p
                        }
                        _ => base_n,
                    },
                    Type::Slice(element) => {
                        let data = self.temp();
                        let p = self.temp();
                        let et = self.ty(element);
                        let _ = writeln!(
                            self.out,
                            "  {data} = extractvalue {{ ptr, i64 }} {base_n}, 0"
                        );
                        let _ = writeln!(
                            self.out,
                            "  {p} = getelementptr inbounds {et}, ptr {data}, i64 {s}"
                        );
                        p
                    }
                    _ => {
                        let loaded = self.temp();
                        let data = self.temp();
                        let p = self.temp();
                        let _ =
                            writeln!(self.out, "  {loaded} = load {{ ptr, i64 }}, ptr {base_n}");
                        let _ = writeln!(
                            self.out,
                            "  {data} = extractvalue {{ ptr, i64 }} {loaded}, 0"
                        );
                        let _ = writeln!(
                            self.out,
                            "  {p} = getelementptr inbounds i64, ptr {data}, i64 {s}"
                        );
                        p
                    }
                };
                let _ = writeln!(
                    self.out,
                    "  {name} = insertvalue {{ ptr, i64 }} {{ ptr poison, i64 0 }}, ptr {data_ptr}, 0"
                );
                let name2 = self.temp();
                let _ = writeln!(
                    self.out,
                    "  {name2} = insertvalue {{ ptr, i64 }} {name}, i64 {len_tmp}, 1"
                );
                // Rename: replace value name mapping to final slice.
                self.value_names.insert(id, name2);
                self.value_types.insert(id, inst.ty.clone());
            }
            InstKind::EnumConstruct {
                enum_name,
                variant_index,
                fields,
            } => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let ety = self
                    .enum_types
                    .get(enum_name)
                    .cloned()
                    .unwrap_or_else(|| format!("%enum.{enum_name}"));
                if fields.is_empty() {
                    let _ = writeln!(
                        self.out,
                        "  {name} = insertvalue {ety} poison, i32 {variant_index}, 0"
                    );
                } else {
                    let mut cur = self.temp();
                    let _ = writeln!(
                        self.out,
                        "  {cur} = insertvalue {ety} poison, i32 {variant_index}, 0"
                    );
                    let info = self.enum_infos.get(enum_name).cloned();
                    for (fi, field_val) in fields.iter().enumerate() {
                        let llvm_idx = self.enum_payload_index(enum_name, *variant_index, fi);
                        let fty = info
                            .as_ref()
                            .and_then(|inf| {
                                inf.variants
                                    .get(*variant_index)
                                    .and_then(|v| v.fields.get(fi).map(|(_, t)| t.clone()))
                            })
                            .unwrap_or(Type::I64);
                        let ft = self.ty(&fty);
                        let fv = self.lookup(*field_val);
                        let tmp = if fi + 1 == fields.len() {
                            name.clone()
                        } else {
                            self.temp()
                        };
                        let _ = writeln!(
                            self.out,
                            "  {tmp} = insertvalue {ety} {cur}, {ft} {fv}, {llvm_idx}"
                        );
                        cur = tmp;
                    }
                }
                self.value_types.insert(id, inst.ty.clone());
            }
            InstKind::EnumTag { value } => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let v = self.lookup(*value);
                let vt = self.value_types.get(value).cloned().unwrap_or(Type::I64);
                let ety = match &vt {
                    Type::Enum(n) => self
                        .enum_types
                        .get(n)
                        .cloned()
                        .unwrap_or_else(|| format!("%enum.{n}")),
                    _ => self.ty(&vt),
                };
                let tag32 = self.temp();
                let _ = writeln!(self.out, "  {tag32} = extractvalue {ety} {v}, 0");
                let _ = writeln!(self.out, "  {name} = zext i32 {tag32} to i64");
                self.value_types.insert(id, Type::I64);
            }
            InstKind::EnumField {
                value,
                variant_index,
                field_index,
            } => {
                let id = inst.id.unwrap();
                let name = self.name_of(id);
                let v = self.lookup(*value);
                let vt = self
                    .value_types
                    .get(value)
                    .cloned()
                    .unwrap_or(inst.ty.clone());
                let (ename, ety) = match &vt {
                    Type::Enum(n) => (
                        n.clone(),
                        self.enum_types
                            .get(n)
                            .cloned()
                            .unwrap_or_else(|| format!("%enum.{n}")),
                    ),
                    _ => (String::new(), self.ty(&vt)),
                };
                let llvm_idx = self.enum_payload_index(&ename, *variant_index, *field_index);
                let fty = self.ty(&inst.ty);
                let _ = writeln!(self.out, "  {name} = extractvalue {ety} {v}, {llvm_idx}");
                let _ = fty;
                self.value_types.insert(id, inst.ty.clone());
            }
        }
    }

    fn emit_term(&mut self, term: &Terminator, ret_ty: &Type) {
        match term {
            Terminator::Return(None) => {
                let _ = writeln!(self.out, "  ret void");
            }
            Terminator::Return(Some(v)) => {
                let name = self.lookup(*v);
                if *ret_ty == Type::Unit {
                    let _ = writeln!(self.out, "  ret void");
                } else {
                    let _ = writeln!(self.out, "  ret {} {name}", self.ty(ret_ty));
                }
            }
            Terminator::Jump(b) => {
                let _ = writeln!(self.out, "  br label %block_{}", b.0);
            }
            Terminator::Branch {
                cond,
                then_block,
                else_block,
            } => {
                let c = self.lookup(*cond);
                let _ = writeln!(
                    self.out,
                    "  br i1 {c}, label %block_{}, label %block_{}",
                    then_block.0, else_block.0
                );
            }
            Terminator::Switch {
                discr,
                cases,
                default,
            } => {
                let d = self.lookup(*discr);
                let mut arms = String::new();
                for (tag, bid) in cases {
                    arms.push_str(&format!(" i64 {tag}, label %block_{}", bid.0));
                }
                let _ = writeln!(
                    self.out,
                    "  switch i64 {d}, label %block_{} [{arms} ]",
                    default.0
                );
            }
            Terminator::Unreachable => {
                let _ = writeln!(self.out, "  unreachable");
            }
        }
    }

    fn ty(&self, t: &Type) -> String {
        match t {
            Type::I64 | Type::Unit | Type::CChar => "i64".into(),
            Type::F64 => "double".into(),
            Type::Bool => "i1".into(),
            Type::Str | Type::Slice(_) => "{ ptr, i64 }".into(),
            Type::CString => "ptr".into(),
            Type::Named(n) | Type::Struct(n) => self
                .struct_types
                .get(n)
                .cloned()
                .unwrap_or_else(|| format!("%struct.{n}")),
            Type::Enum(n) => self
                .enum_types
                .get(n)
                .cloned()
                .unwrap_or_else(|| format!("%enum.{n}")),
            // `&[T]` / `&mut [T]` are fat pointers, like `str`.
            Type::Ref { inner, .. } if matches!(inner.as_ref(), Type::Slice(_)) => {
                "{ ptr, i64 }".into()
            }
            Type::Ref { .. } => "ptr".into(),
            Type::Array { element, len } => format!("[{len} x {}]", self.ty(element)),
        }
    }

    fn enum_payload_index(
        &self,
        enum_name: &str,
        variant_index: usize,
        field_index: usize,
    ) -> usize {
        let Some(info) = self.enum_infos.get(enum_name) else {
            return 1 + field_index;
        };
        let mut idx = 1usize; // tag at 0
        for (i, v) in info.variants.iter().enumerate() {
            if i == variant_index {
                return idx + field_index;
            }
            idx += v.fields.len();
        }
        idx + field_index
    }

    fn ret_ty(&self, t: &Type) -> String {
        if *t == Type::Unit {
            "void".into()
        } else {
            self.ty(t)
        }
    }

    fn name_of(&mut self, id: ValueId) -> String {
        let name = format!("%v{}", id.0);
        self.value_names.insert(id, name.clone());
        name
    }

    fn lookup(&self, id: ValueId) -> String {
        self.value_names
            .get(&id)
            .cloned()
            .unwrap_or_else(|| format!("%v{}", id.0))
    }

    fn temp(&mut self) -> String {
        let n = self.next_temp;
        self.next_temp += 1;
        format!("%t{n}")
    }
}

fn block_label(block: &BasicBlock) -> String {
    format!("block_{}", block.id.0)
}

fn mangle(name: &str) -> String {
    // Keep names as-is for C ABI friendliness.
    name.to_string()
}

fn llvm_escape(s: &str) -> String {
    let mut out = String::new();
    for b in s.bytes() {
        match b {
            b'\\' => out.push_str("\\\\"),
            b'"' => out.push_str("\\22"),
            0x07 => out.push_str("\\07"),
            0x08 => out.push_str("\\08"),
            0x09 => out.push_str("\\09"),
            0x0a => out.push_str("\\0A"),
            0x0d => out.push_str("\\0D"),
            0x20..=0x7e => out.push(b as char),
            _ => out.push_str(&format!("\\{b:02X}")),
        }
    }
    out
}
